language: cpp
os: 
  - osx
  - linux
compiler: clang
env:
  - BUILD_CONFIG=Debug
osx_image: xcode7.3

sudo: required
dist: trusty
      
install: ./ci/travis/install.sh
  
before_script:
  - cmake --version
  - mkdir build && cd build
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      cmake .. -GNinja $CMAKE_ARGS
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      cmake .. -G "Unix Makefiles" $CMAKE_ARGS
    fi
    
script:
  - cmake --build . --target $CMAKE_TARGET --config $BUILD_CONFIG && ctest -C $BUILD_CONFIG -V

notifications:
  email:
    on_failure: change
    on_success: change
