language: cpp
os: 
  - osx
  - linux
compiler: clang
env:
  - BUILD_CONFIG=Debug 

osx_image: xcode7.3

sudo: required
dist: trusty
      
install: ./ci/travis/install.sh
  
before_script: ./ci/travis/make_build.sh
    
script:
  - cd build && cmake --build . --target GworkNullSample --config $BUILD_CONFIG 

notifications:
  email:
    on_failure: change
    on_success: change
